apiVersion: v1
kind: Service
metadata:
  name: nginx-state
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: nginx
Transform: AWS::Serverless-2016-10-31
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: Api
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /:
            get:
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
  Queue:
    Type: AWS::SQS::Queue